# Generated by Django 3.1 on 2020-08-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200830_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField()),
                ('starting_date', models.DateTimeField()),
                ('students', models.ManyToManyField(related_name='student_id', to='students.Student')),
            ],
        ),
    ]
