# Generated by Django 3.1 on 2020-09-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rating',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
