# Generated by Django 3.1 on 2020-09-27 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_date',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='write_date',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='create_date',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='write_date',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
