# Generated by Django 3.1 on 2020-09-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200927_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='write_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='write_date',
        ),
    ]
