# Generated by Django 3.1 on 2020-09-27 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20200927_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='write_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='write_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
