# Generated by Django 3.1 on 2020-09-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='classrooms',
            field=models.ManyToManyField(related_name='groups', to='groups.Classroom'),
        ),
    ]
