# Generated by Django 3.1 on 2020-09-27 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_group_classrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
